default_language_version:
  python: python3.10
default_stages: [commit]
fail_fast: true
exclude: ".apps.py"

repos:

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: check-merge-conflict


  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        args: [-l  88]
        exclude: "hooks/post_*"


  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-no-log-warn
      - id: python-no-eval
      - id: text-unicode-replacement-char
